### PR TITLE
Bring things up to date

### PR DESCRIPTION
**Pull request by bgamari**
This adds support for Cabal 0.21.

### CODE REVIEW

**Comment by RyanGlScott** [comment]
This patch (as well as bumping the upper bounds of `base` to < 4.9) allows me to build `packunused` with GHC 7.10.

**Comment by RyanGlScott** [comment]
@bgamari: I think the Travis builds are failing because the latest version of `Cabal` on Hackage is 1.22.0.0, which cannot be used due to the upper version bounds. Can you bump it to `Cabal < 1.23` and see if it works?

**Comment by hvr** [comment]
I'm actually surprised actually the `MIN_VERSION_Cabal()` macro has wrong arguments... you also may want to add to update the `.travis.yml` file to include GHC 7.10.1 + cabal-install 1.22 in the build-matrix

**Comment by bgamari** [comment]
@hvr indeed.

**Comment by hvr** [comment]
fyi, I just uploaded http://hackage.haskell.org/package/packunused-0.1.1.4

**Pull request merged**
