### PR TITLE
Bump bounds for haskell-src-exts and process

### PR DESCRIPTION
**Pull request by lwm**

### CODE REVIEW

**Comment by hvr** [comment]
@lwm did you give it a test-run to see if it still works as expected?

**Comment by lwm** [comment]
I ran a `stack build` and it compiled.

Bounds bump came from http://packdeps.haskellers.com/feed/packunused.

**Comment by hvr** [comment]
@lwm well, didn't mean merely compile it (that's also what Travis CI already confirmed), but actually using the resulting `packunused` on some package to see if it still works :-)

**Comment by lwm** [comment]
> but actually using the resulting packunused on some package to see if it still works :-)

Ah! It seems like a motivating reason for an integration test :) Let's see what I can do.

**Comment by lwm** [comment]
Right, I realised that you generate the Travis file, so not much use putting some test in there! I've manually tested the latest changes and things are working:

``` bash
diff --git a/packunused.cabal b/packunused.cabal
index e87ad4d..460bfe1 100644
--- a/packunused.cabal
+++ b/packunused.cabal
@@ -84,3 +84,4 @@ executable packunused
                , haskell-src-exts     >= 1.18.2 && < 1.20
                , process              >= 1.1    && < 1.7
                , split                >= 0.2    && < 0.3
+               , criterion
λ ~/hobby/packunused/ bump-bounds*  stack setup --upgrade-cabal
 stack clean
 stack build --ghc-options '-ddump-minimal-imports -O0'
 packunused
Currently installed Cabal is 1.24.2.0, newest is 1.24.2.0. I'm not upgrading Cabal.
stack will use a sandboxed GHC it installed
For more information on paths, see 'stack path' and 'stack exec env'
To use this GHC and packages outside of a project, consider using:
stack ghc, stack ghci, stack runghc, or stack exec
Glob-0.7.14: using precompiled package
abstract-deque-0.3: download
code-page-0.1.3: download
abstract-par-0.3.3: download
abstract-deque-0.3: configure
cassava-0.4.5.1: download
abstract-deque-0.3: build
code-page-0.1.3: configure
code-page-0.1.3: build
abstract-par-0.3.3: configure
abstract-par-0.3.3: build
cassava-0.4.5.1: configure
code-page-0.1.3: copy/register
abstract-deque-0.3: copy/register
abstract-par-0.3.3: copy/register
ieee754-0.8.0: using precompiled package
cassava-0.4.5.1: build
hastache-0.6.1: using precompiled package
erf-2.0.0.0: download
js-flot-0.8.3: download
erf-2.0.0.0: configure
js-jquery-3.1.1: download
erf-2.0.0.0: build
js-jquery-3.1.1: configure
erf-2.0.0.0: copy/register
js-jquery-3.1.1: build
js-jquery-3.1.1: copy/register
js-flot-0.8.3: configure
js-flot-0.8.3: build
monad-par-extras-0.3.3: download
vector-binary-instances-0.2.3.5: download
monad-par-extras-0.3.3: configure
monad-par-extras-0.3.3: build
monad-par-extras-0.3.3: configure
monad-par-extras-0.3.3: build
vector-binary-instances-0.2.3.5: configure
vector-binary-instances-0.2.3.5: build
js-flot-0.8.3: copy/register
monad-par-extras-0.3.3: copy/register
vector-binary-instances-0.2.3.5: copy/register
monad-par-0.3.4.8: download
monad-par-0.3.4.8: configure
monad-par-0.3.4.8: build
monad-par-0.3.4.8: copy/register
cassava-0.4.5.1: copy/register
statistics-0.13.3.0: download
statistics-0.13.3.0: configure
statistics-0.13.3.0: build
statistics-0.13.3.0: copy/register
criterion-1.1.4.0: download
criterion-1.1.4.0: configure
criterion-1.1.4.0: build
Progress: 14/16

criterion-1.1.4.0: copy/register
packunused-0.1.2: configure (exe)
Configuring packunused-0.1.2...
packunused-0.1.2: build (exe)
Preprocessing executable 'packunused' for packunused-0.1.2...
[1 of 2] Compiling Paths_packunused ( .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/autogen/Paths_packunused.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/packunused/packunused-tmp/Paths_packunused.o )
[2 of 2] Compiling Main             ( packunused.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/packunused/packunused-tmp/Main.o )
Linking .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/packunused/packunused ...
packunused-0.1.2: copy/register
Installing executable(s) in
/home/lwm/hobby/packunused/.stack-work/install/x86_64-linux/lts-8.13/8.0.2/bin
Completed 16 action(s).
detected package components
~~~~~~~~~~~~~~~~~~~~~~~~~~~

 - executable(s): packunused

(component names suffixed with '*' are not configured to be built)

executable(packunused)
~~~~~~~~~~~~~~~~~~~~~~

The following package dependencies seem redundant:

 - criterion-1.1.4.0-XPX5z6PsNAJ6zvxEYXky3

```

:+1:

**Comment by hvr** [comment]
Thanks!

**Comment by hvr** [comment]
...and see also  http://hackage.haskell.org/package/packunused-0.1.2/revisions/

**Pull request merged**
