### PR TITLE
Remove comment cruft. Bump to latest LTS.

### PR DESCRIPTION
**Pull request by lwm**
After cloning HEAD and running `stack build` I was getting a dependency conflict.

I was able to build after bumping the LTS.

### CODE REVIEW

**Comment by hvr** [comment]
thanks, I don't use stack myself, so I don't manage the stack.yaml myself

**Comment by lwm** [comment]
@hvr Cool, maybe I can add a Stack build to the `.travis.yml`

**Comment by lwm** [comment]
@hvr Question: I see the `.travis.yml` file was generated by `hvr/multi-ghc-travis` which doesn't add Stack support. Should I submit a PR at `hrv/multi-ghc-travis` which adds Stack support or just hack it into the `.travis.yml` in this repo?

**Comment by hvr** [comment]
@lwm adding it to multi-ghc-travis makes little sense, the plan is to support testing against LTS snapshots via cabal (you can see a prototype in action here: https://travis-ci.org/hvr/cassava/builds/174906534); after all, if something builds with cabal it's almost guaranteed to build with stack too (it's the other way round that's more problematic usually); so there is no need to rely on Stack, as that would only complicate what I have in mind for multi-ghc-travis.

**Comment by lwm** [comment]
Ah, I see. Well, I'll let that one go then. Thanks for the explanation.

It's pretty simple to update the `stack.yaml` when necessary.

**Pull request merged**
